### PR TITLE
Fix support for mediawiki 1.31

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by Alexia** [comment]
Looks good to me.  I will merge it in at a later date when MW 1.31 is fully released.

**Comment by paladox** [comment]
@Alexia this should work in mw 1.30 too and all the other mw releases that support extension.json (except probaly 1.25 and 1.26)

**Comment by paladox** [comment]
https://github.com/search?l=JSON&q=org%3Awikimedia+FileExtensions&type=Code

**Comment by paladox** [comment]
bump @Alexia

**Comment by paladox** [comment]
ping @Alexia mw 1.31 has been released.

**Comment by paladox** [comment]
bump

**Pull request merged**
